name: Build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/setup-go@v2
        with:
          go-version: "^1.16.4"

      - name: Build App
        run: |
          go build .

      - name: Run command
        run: |
          echo some text